#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BlockError {
    NceBadFormat,
    NceBugBadGCodeModalGroup0,
    NceCannotPutAnAInCannedCycle,
    NceCannotUseAxisValuesWithoutAGcodeThatUsesThem,
    NceCannotUseAxisValuesWithG80,
    NceCannotUseG53Incremental,
    NceLineWithG10DoesNotHavel2,
    NceUnclosedCommentFound,
    NcePValueNotAnIntegerWithG10L2,
    NcePValueOutOfRangeWithG10L2,
    NceSscanfFailed,

    NceGCODEOutOfRange,
    NceMCODEOutOfRange,
    NceMCodeGreaterThan99,
    NceLineNumberGreaterThan99999,

    NceNegativeOrZeroQValueUsed,
    NceNegativeFWordUsed,
    NceNegativePWordUsed,
    NceNegativeHWordToolLengthOffsetIndexUsed,
    NceNegativeLWordUsed,
    NceNegativeMCodeUsed,

    NceMultipleWordsOnOneLine,
    NceMultipleAWordsOnOneLine,
    NceTwoMCodesUsedFromSameModalGroup,
    NceCannotUseTwoGCodethatBothUseAxisValues,
    NceTooManyMCodesOnLine,

    NceDWordWithNoG41OrG42,
    NceDwellTimeMissingWithG4,
    NceHWordWithNoG43,
    NceIWordWithNoG2OrG3OrG87ToUseIT,
    NceJWordWithNoG2OrG3OrG87ToUseIT,
    NceKWordWithNoG2OrG3OrG87ToUseIT,
    NceLWordWithNoCannedCycleOrG10,
    NcePWordwithNoG4G10G82G86G88G89,
    NceQWordWithNoG83,
    NceRwordWithNoGCodeThatUseIT,
    NceMustUseG0OrG1WithG53,
    NceAllAxesMissingWithG92,
    NceAllAxesMissingWithMotionCode,
}
